import { VerticalVideoData } from './types';

/** 10-Second Teaser Clip (300 frames @ 30fps) */
export const GEMINI_4_PRO_TEASER_PROPS: VerticalVideoData = {
  topic: 'Gemini 4 Pro',
  brandPill: '✦ GOOGLE DEEPMIND • NEXT GEN AI',
  totalDurationFrames: 300,
  voiceoverAudio: 'audio/voiceover_teaser.mp3',
  bgmAudio: 'audio/bgm.mp3',
  bgmVolume: 0.18,
  voiceoverVolume: 1.0,
  scenes: [
    {
      id: 1,
      durationInFrames: 150, // 5 seconds
      tag: '✦ BREAKING DISRUPTION',
      headline: 'FORGET EVERYTHING',
      highlightWord: 'EVERYTHING',
      subhead: 'Google just unlocked next-generation intelligence.',
      accentColor: '#38bdf8',
      sceneType: 'core',
      subtitles: [
        { word: 'Forget', startFrame: 8, endFrame: 22 },
        { word: 'everything', startFrame: 22, endFrame: 40 },
        { word: 'you', startFrame: 40, endFrame: 50 },
        { word: 'know', startFrame: 50, endFrame: 62 },
        { word: 'about', startFrame: 62, endFrame: 74 },
        { word: 'artificial', startFrame: 74, endFrame: 92 },
        { word: 'intelligence.', startFrame: 92, endFrame: 125 },
      ],
    },
    {
      id: 2,
      durationInFrames: 150, // 5 seconds
      tag: '✦ 10M REASONING CONTEXT',
      headline: '10 MILLION TOKENS',
      highlightWord: 'TOKENS',
      subhead: 'Autonomous full-stack engineering at scale.',
      accentColor: '#818cf8',
      sceneType: 'specs',
      metricValue: '10,000,000',
      metricLabel: 'Active Context Capacity',
      subtitles: [
        { word: 'Meet', startFrame: 8, endFrame: 20 },
        { word: 'Gemini', startFrame: 20, endFrame: 34 },
        { word: '4', startFrame: 34, endFrame: 46 },
        { word: 'Pro.', startFrame: 46, endFrame: 62 },
        { word: 'A', startFrame: 62, endFrame: 72 },
        { word: 'ten', startFrame: 72, endFrame: 84 },
        { word: 'million', startFrame: 84, endFrame: 98 },
        { word: 'token', startFrame: 98, endFrame: 112 },
        { word: 'context', startFrame: 112, endFrame: 126 },
        { word: 'window.', startFrame: 126, endFrame: 144 },
      ],
    },
  ],
};

/** Full 30-Second Vertical Short (900 frames @ 30fps) */
export const GEMINI_4_PRO_FULL_PROPS: VerticalVideoData = {
  topic: 'Gemini 4 Pro',
  brandPill: '✦ GOOGLE DEEPMIND • NEXT GEN AI',
  totalDurationFrames: 900,
  voiceoverAudio: 'audio/voiceover.mp3',
  bgmAudio: 'audio/bgm.mp3',
  bgmVolume: 0.18,
  voiceoverVolume: 1.0,
  scenes: [
    {
      id: 1,
      durationInFrames: 180, // 6 seconds (0 - 180)
      tag: '✦ BREAKING DISRUPTION',
      headline: 'FORGET EVERYTHING',
      highlightWord: 'EVERYTHING',
      subhead: 'The AI ceiling didn’t just break. It vanished.',
      accentColor: '#38bdf8',
      sceneType: 'core',
      subtitles: [
        { word: 'Forget', startFrame: 8, endFrame: 22 },
        { word: 'everything', startFrame: 22, endFrame: 42 },
        { word: 'you', startFrame: 42, endFrame: 54 },
        { word: 'know', startFrame: 54, endFrame: 68 },
        { word: 'about', startFrame: 68, endFrame: 82 },
        { word: 'AI.', startFrame: 82, endFrame: 104 },
        { word: 'Google', startFrame: 104, endFrame: 122 },
        { word: 'just', startFrame: 122, endFrame: 136 },
        { word: 'unlocked', startFrame: 136, endFrame: 154 },
        { word: 'true', startFrame: 154, endFrame: 166 },
        { word: 'AGI.', startFrame: 166, endFrame: 178 },
      ],
    },
    {
      id: 2,
      durationInFrames: 240, // 8 seconds (180 - 420)
      tag: '✦ 10M REASONING CONTEXT',
      headline: '10 MILLION TOKENS',
      highlightWord: 'TOKENS',
      subhead: 'Autonomous full-stack engineering at scale.',
      accentColor: '#818cf8',
      sceneType: 'specs',
      metricValue: '10,000,000',
      metricLabel: 'Active Context Capacity',
      subtitles: [
        { word: 'Meet', startFrame: 8, endFrame: 22 },
        { word: 'Gemini', startFrame: 22, endFrame: 38 },
        { word: '4', startFrame: 38, endFrame: 50 },
        { word: 'Pro.', startFrame: 50, endFrame: 72 },
        { word: 'Ten', startFrame: 72, endFrame: 88 },
        { word: 'million', startFrame: 88, endFrame: 106 },
        { word: 'tokens', startFrame: 106, endFrame: 124 },
        { word: 'that', startFrame: 124, endFrame: 138 },
        { word: 'code,', startFrame: 138, endFrame: 156 },
        { word: 'deploy,', startFrame: 156, endFrame: 178 },
        { word: 'and', startFrame: 178, endFrame: 192 },
        { word: 'scale', startFrame: 192, endFrame: 210 },
        { word: 'autonomously.', startFrame: 210, endFrame: 236 },
      ],
    },
    {
      id: 3,
      durationInFrames: 240, // 8 seconds (420 - 660)
      tag: '✦ WORLD RECORD BENCHMARKS',
      headline: '98.4% REASONING',
      highlightWord: 'REASONING',
      subhead: '10x faster execution with unprecedented accuracy.',
      accentColor: '#34d399',
      sceneType: 'benchmark',
      comparisonItems: [
        { label: 'Gemini 4 Pro', score: 98.4, displayValue: '98.4%', isHighlight: true, color: '#34d399' },
        { label: 'OpenAI o3-mini', score: 86.2, displayValue: '86.2%', isHighlight: false, color: '#64748b' },
        { label: 'Claude 3.5 Sonnet', score: 82.0, displayValue: '82.0%', isHighlight: false, color: '#64748b' },
        { label: 'GPT-4.5 Preview', score: 78.5, displayValue: '78.5%', isHighlight: false, color: '#64748b' },
      ],
      subtitles: [
        { word: 'Shattering', startFrame: 8, endFrame: 28 },
        { word: 'world', startFrame: 28, endFrame: 44 },
        { word: 'records', startFrame: 44, endFrame: 64 },
        { word: 'with', startFrame: 64, endFrame: 78 },
        { word: 'a', startFrame: 78, endFrame: 88 },
        { word: 'ninety-eight', startFrame: 88, endFrame: 112 },
        { word: 'point', startFrame: 112, endFrame: 126 },
        { word: 'four', startFrame: 126, endFrame: 140 },
        { word: 'percent', startFrame: 140, endFrame: 160 },
        { word: 'reasoning', startFrame: 160, endFrame: 182 },
        { word: 'benchmark.', startFrame: 182, endFrame: 232 },
      ],
    },
    {
      id: 4,
      durationInFrames: 240, // 8 seconds (660 - 900)
      tag: '✦ IMMEDIATE ACCESS',
      headline: 'BUILD THE FUTURE',
      highlightWord: 'FUTURE',
      subhead: 'Available today worldwide in Google AI Studio.',
      accentColor: '#fbbf24',
      sceneType: 'cta',
      ctaButtonText: 'Try Gemini 4 Pro',
      ctaUrl: 'ai.google.dev/gemini-4',
      subtitles: [
        { word: 'The', startFrame: 8, endFrame: 20 },
        { word: 'future', startFrame: 20, endFrame: 38 },
        { word: 'is', startFrame: 38, endFrame: 50 },
        { word: 'here.', startFrame: 50, endFrame: 74 },
        { word: 'Experience', startFrame: 74, endFrame: 98 },
        { word: 'Gemini', startFrame: 98, endFrame: 116 },
        { word: '4', startFrame: 116, endFrame: 130 },
        { word: 'Pro', startFrame: 130, endFrame: 152 },
        { word: 'today', startFrame: 152, endFrame: 174 },
        { word: 'on', startFrame: 174, endFrame: 188 },
        { word: 'AI', startFrame: 188, endFrame: 204 },
        { word: 'Studio.', startFrame: 204, endFrame: 234 },
      ],
    },
  ],
};
